W8D1/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:create, :new, :show, :index]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy]
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create, :show]
end

W8D1/app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, :post_id, :author_id, presence: true

  belongs_to :author,
    foreign_key: :author_id,
    class_name: :User

  belongs_to :post,
    foreign_key: :post_id,
    class_name: :Post

  belongs_to :parent_comment,
    foreign_key: :parent_comment_id,
    class_name: :Comment,
    optional: true

  has_many :child_comments,
    foreign_key: :parent_comment_id,
    class_name: :Comment
end

W8D1/app/models/post.rb
class Post < ApplicationRecord
  validates :title, :author_id, presence: true

  belongs_to :author,
    foreign_key: :author_id,
    class_name: :User

  has_many :post_subs,
    foreign_key: :post_id,
    class_name: :PostSub,
    dependent: :destroy,
    inverse_of: :post

  has_many :subs,
    through: :post_subs,
    source: :sub

  has_many :comments,
    foreign_key: :post_id,
    class_name: :Comment
end

W8D1/app/models/post_sub.rb
class PostSub < ApplicationRecord

  belongs_to :sub,
    foreign_key: :sub_id,
    class_name: :Sub

  belongs_to :post,
    foreign_key: :post_id,
    class_name: :Post
    
end

W8D1/app/models/sub.rb
class Sub < ApplicationRecord

  validates :title, :description, :moderator_id, presence: true
  validates :title, uniqueness: true

  belongs_to :moderator,
    foreign_key: :moderator_id,
    class_name: :User

  has_many :post_subs,
    foreign_key: :sub_id,
    class_name: :PostSub,
    dependent: :destroy,
    inverse_of: :sub

  has_many :posts,
    through: :post_subs,
    source: :post

end

W8D1/app/models/user.rb
class User < ApplicationRecord
  validates :username, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  after_initialize :ensure_session_token

  has_many :subs,
    foreign_key: :moderator_id,
    class_name: :Sub

  has_many :posts,
    foreign_key: :author_id,
    class_name: :Post

  has_many :comments,
    foreign_key: :author_id,
    class_name: :Comment

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    if user && user.is_password?(password)
      user
    else
      nil
    end
  end

  attr_reader :password
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end
end

W8D1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def logged_in?
    !!current_user
  end

  def login!(user)
    session[:session_token] = user.reset_session_token! 
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
  end
end

W8D1/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new

    render :new
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to post_url(@comment.post)
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end
  
  def show
    @comment = Comment.find_by(id: params[:id])

    render :show
  end

  private
  def comment_params
    params.require(:comment).permit(:content,:parent_comment_id, :post_id, :author_id)
  end
end

W8D1/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :is_author?, only: [:edit, :update, :destroy]

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    redirect_to subs_url
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def new
    @post = Post.new
    render :new
  end

  def edit
    @post = Post.find_by(id: params[:id])
    render :edit
  end

  def show
    @post = Post.find_by(id: params[:id])
    render :show
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = ["Couldn't update!"]
      render :edit
    end
  end

  private
  def is_author?
    @post = Post.find_by(id: params[:id])
    unless current_user.posts.include?(@post)
      flash[:errors] = ["You are not the author of this post."]
      redirect_to post_url(@post)
    end
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

W8D1/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username],params[:user][:password])
    if @user
      login!(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = ["Invalid Credentials"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

W8D1/app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :is_moderator?, only: [:edit, :update]

  def index
    @subs = Sub.all
    render :index
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def new
    @sub = Sub.new
    render :new
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
    render :edit
  end

  def show
    @sub = Sub.find_by(id: params[:id])
    render :show
  end

  def update
    @sub = Sub.find_by(id: params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = ["Couldn't update!"]
      render :edit
    end
  end

  private
  def is_moderator?
    @sub = Sub.find_by(id: params[:id])
    unless current_user.subs.include?(@sub)
      flash[:errors] = ["You are not the moderator of this sub."]
      redirect_to sub_url(@sub)
    end
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end


end

W8D1/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index 
    @users = User.all

    render :index
  end

  def show
    @user = User.find_by(id: params[:id])

    render :show
  end

  def new
    @user = User.new

    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

W8D1/app/helpers/comments_helper.rb
module CommentsHelper
end

W8D1/app/helpers/posts_helper.rb
module PostsHelper
end

W8D1/app/helpers/sessions_helper.rb
module SessionsHelper
end

W8D1/app/helpers/users_helper.rb
module UsersHelper
end

W8D1/app/views/comments/new.html.erb
<h1>Write a comment</h1>

<form action="<%=comments_url%>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label>Content
    <input type="text" name="comment[content]" value="<%= @comment.content %>">
  </label>
  <input type="hidden" name="comment[author_id]" value="<%=current_user.id%>">
  <input type="hidden" name="comment[post_id]" value="<%=params[:post_id]%>">
  <input type="submit" value="Post Comment">
</form>

W8D1/app/views/comments/show.html.erb
<h1><%= @comment.author.username %>'s Comment</h1>
<p><%= @comment.content %></p>

<h2>Replies</h2>
<form action="<%=comments_url%>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label>Content
    <input type="text" name="comment[content]" value="">
  </label>
  <input type="hidden" name="comment[author_id]" value="<%=current_user.id%>">
  <input type="hidden" name="comment[post_id]" value="<%=@comment.post_id%>">
  <input type="hidden" name="comment[parent_comment_id]" value="<%=@comment.id%>">
  <input type="submit" value="Post Comment">
</form>
<ul>
  <% @comment.child_comments.each do |child| %>
    <li>
        <p>Posted By: <%= child.author.username %></p>
        <p><%= child.content %></p>
      </li>
  <% end %>
</ul>

W8D1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=flash[:errors]%>
    
    <a href="<%= subs_url %>">All Subs</a>
    <% if logged_in? %>
    <a href="<%= users_url %>">All Users</a>
      <p>Logged in as: <%= current_user.username %></p>
      <form action="<%= session_url %>" method="POST">
        <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Log Out">
      </form>

      <a href="<%= new_sub_url %>">Create a sub</a>
      <a href="<%= new_post_url %>">Create a post</a>
    <% else %>
      <a href="<%= new_user_url %>">Sign Up</a>
      <a href="<%= new_session_url %>">Sign In</a>
    <% end %>
    <%= yield %>
  </body>
</html>

W8D1/app/views/subs/edit.html.erb
<h1>Editing <%= @sub.title %> </h1>

<form action="<%= sub_url(@sub) %>" method="POST">
  <input type="hidden" name="authenticity_token" value= "<%=form_authenticity_token%>">
  <input type="hidden" name="_method" value= "PATCH">

  <label>Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>
  <label>Description
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label>
  <input type="submit" value="Edit Sub">
</form>

W8D1/app/views/subs/index.html.erb
<h1>All subs!</h1>

<ul>
  <% @subs.each do |sub| %>
    <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a></li>
  <% end %>
</ul>

W8D1/app/views/subs/new.html.erb
<h1>Create a new Sub</h1>

<form action="<%= subs_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value= "<%=form_authenticity_token%>">

  <label>Title
    <input type="text" name="sub[title]" value="<%=@sub.title%>">
  </label>
  <label>Description
    <input type="text" name="sub[description]" >
  </label>
  <input type="submit" value="Create Sub">
</form>

W8D1/app/views/subs/show.html.erb
<h1>Welcome to <%= @sub.title %></h1>
<a href="<%= edit_sub_url(@sub) %>">Edit Sub</a>
<h2>Created by <%= @sub.moderator.username %></h2>
<p><%= @sub.description %></p>

<h2>Posts</h2>

<% unless @sub.posts.empty? %>
  <ul>
    <% @sub.posts.each do |post| %>
      <li><a href="<%=post_url(post)%>"><%= post.title %></a></li>
    <% end %>
  </ul>
<% else %>
  <p><%= @sub.title %> has no posts</p>
<% end %>

W8D1/app/views/users/index.html.erb
<h1>Here are our users</h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <a href="<%=user_url(user)%>"><%= user.username %></a>
    </li>
  <% end %>
</ul>

W8D1/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%=users_url%>" method="POST">
  <input type="hidden" name="authenticity_token" value= "<%=form_authenticity_token%>">

  <label>Username
    <input type="text" name="user[username]" value="<%=@user.username%>">
  </label>
  <label>Password
    <input type="password" name="user[password]" >
  </label>
  <input type="submit" value="Create Account">
</form>

W8D1/app/views/users/show.html.erb
<h1><%= @user.username %>'s Profile </h1>
<% unless @user.subs.empty? %>
  <h2>Moderator of</h2>
  <ul>
    <% @user.subs.each do |sub| %>
      <li><a href="<%=sub_url(sub)%>"><%= sub.title %></a></li>
    <% end %>
  </ul>
<% end %>

<h2>Posts</h2>

<% unless @user.posts.empty? %>
  <ul>
    <% @user.posts.each do |post| %>
      <li><a href="<%=post_url(post)%>"><%= post.title %></a></li>
    <% end %>
  </ul>
<% else %>
  <p><%= @user.username %> has no posts</p>
<% end %>

<h2>Comments</h2>
<% unless @user.comments.empty? %>
  <ul>
    <% @user.comments.each do |comment| %>

      <li><%= comment.content %> - Posted in <%=comment.post.title%></li>
    <% end %>
  </ul>
<% else %>
  <p><%= @user.username %> has no comments</p>
<% end %>